### ISSUE TITLE
Issues with rails server

### ISSUE THREAD

**Issue by kinsomicrote** [straydogstudio/axlsx_rails#34] opened 2015-06-23 20:53 UTC
I run into issues with rails server because of axlsx gem
This is the error:
warning: already initialized constant APP_PATH.

I couldn't find a solution to it so i had to switch gems as i needed to make some new changes to the app.

Though I'll love to use this gem in a later app.

**Comment by straydogstudio** [comment] 2015-06-23 21:01
Which version of Rails, axlsx, and axlsx_rails?

**Comment by kinsomicrote** [comment] 2015-06-23 21:04
Rails version is 4.2.0
I just added gem axlsx_rails in in gemfile

**Comment by straydogstudio** [comment] 2015-06-23 21:34
Look in your Gemfile.lock and let me know what version it is anyway. Or, make a gist of your Gemfile.lock. That way I can find the conflict. Thanks.

**Comment by straydogstudio** [comment] 2015-06-25 04:35
@kinsomicrote FYI, the reason I ask is there are plenty of installations with 4.2 and the latest axlsx_rails with no issues. So I'm not sure what is causing the issue. Perhaps a dependency?

**Comment by kinsomicrote** [comment] 2015-06-25 07:33
Okay. I would check it out when on pc and get back to you. Also can I use axlsx_rails to send form data to xlsx or Google spreadsheet

**Comment by kinsomicrote** [comment] 2015-06-25 07:36
As I want to be able to send form data to either and also out put it to view.

**Comment by straydogstudio** [comment] 2015-06-25 17:15
You can certainly use form data to create a spreadsheet. axlsx_rails is oriented towards generating and returning a single spreadsheet per request. Generating and storing spreadsheets in Google is possible but I've not done it. I believe you need to turn on or off shared strings in Axlsx. See this issue: https://github.com/straydogstudio/axlsx_rails/issues/27

**Comment by straydogstudio** [comment] 2015-08-04 02:30
@kinsomicrote I'm going to close this for now. If you come back to this reopen this issue and we can pick up where we left off.

**Closed by straydogstudio** 2015-08-04 02:30 UTC

**Comment by inopinatus** [comment] 2015-08-31 05:44
I also have this issue but have not yet isolated the cause. Rails 4.2.3 application with Ruby 2.2.2p95, axlsx 1.3.6, axlsx_rails 0.1.5.

**Comment by inopinatus** [comment] 2015-08-31 06:02
This turned out to be a library problem in axlsx; adding the compatibility rubyzip gem with `gem 'zip-zip'` to Gemfile resolved the issue. See also randym/axlsx#234.

**Comment by inopinatus** [comment] 2015-08-31 06:22
.. which of course broke axlsx. Better working solution was adding `gem 'axlsx', '~> 2.0'` to Gemfile.

**Comment by LIYINGZHEN** [comment] 2015-09-02 02:44
@inopinatus Your are right.
Specify `gem 'axlsx', '~> 2.0'` can solve the problem.
